version: "3"
services:
  data-workspace:
    build:
      context: .
      dockerfile: Dockerfile
    image: data-workspace
    ports:
      - "8000:8000"
    env_file: .envs/dev.env
    links:
      - "data-workspace-postgres"
      - "data-workspace-redis"
    volumes:
      - ./dataworkspace:/dataworkspace
    command: |
      sh -c '/bin/sh -s <<EOF
      set -e

      (
          cd "$$(dirname "$$0")"

          django-admin migrate

          django-admin ensure_databases_configured
          django-admin ensure_application_template_models

          echo "Starting proxy and django dev server"
          parallel --will-cite --line-buffer --jobs 2 --halt now,fail=1 ::: \
              "django-admin runserver 8002" \
              "PROXY_PORT=8000 UPSTREAM_ROOT=http://localhost:8002 python3 -m proxy"
      )
      EOF'
  data-workspace-postgres:
    build:
      context: postgres
      dockerfile: Dockerfile
    image: data-workspace-postgres
    ports:
      - "5432:5432"
  data-workspace-redis:
    build:
      context: redis
      dockerfile: Dockerfile
    image: data-workspace-redis
    ports:
      - "6379:6379"
