version: 2

jobs:
  docker-test-integration:
    docker:
      - image: circleci/python:3.7
    resource_class: small
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker images
          command: |
            touch .envs/dev.env
            make docker-build
      - run:
          name: Run integration tests
          command: make docker-test-integration
  docker-test-unit:
    docker:
      - image: circleci/python:3.7
    resource_class: small
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker images
          command: |
            touch .envs/dev.env
            make docker-build
      - run:
          name: Run unit tests
          command: make docker-test-unit
  check-linting:
    docker:
      - image: circleci/python:3.7
    resource_class: small
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install requirements
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements-dev.txt
      - run:
          name: Run static checks
          command: |
            . venv/bin/activate
            make check

workflows:
  version: 2
  build:
    jobs:
      - check-linting
      - docker-test-unit
      - docker-test-integration
